config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :orders
  resources :users
  resources :shippers
  resources :carriers
  resources :brokers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :carrier
  belongs_to :orderer, polymorphic: true

  validates :delivery_address,
            :equipment_type,
            :orderer_id,
            :orderer_type,
            :pickup_address,
            :pickup_date,
            :status,
            presence: true
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show; end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit; end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html do
          redirect_to order_url(@order),
                      notice: 'Order was successfully created.'
        end
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @order.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html do
          redirect_to order_url(@order),
                      notice: 'Order was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @order.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html do
        redirect_to orders_url, notice: 'Order was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.require(:order).permit(:carrier_id, :delivery_address, :equipment_type, :orderer_id, :orderer_type,
                                  :pickup_date, :pickup_address, :status)
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :carrier_id, style: "display: block" %>
    <%= form.text_field :carrier_id %>
  </div>

  <div>
    <%= form.label :delivery_address, style: "display: block" %>
    <%= form.text_field :delivery_address %>
  </div>

  <div>
    <%= form.label :equipment_type, style: "display: block" %>
    <%= form.number_field :equipment_type %>
  </div>

  <div>
    <%= form.label :orderer_id, style: "display: block" %>
    <%= form.text_field :orderer_id %>
  </div>

  <div>
    <%= form.label :pickup_date, style: "display: block" %>
    <%= form.date_field :pickup_date %>
  </div>

  <div>
    <%= form.label :pickup_address, style: "display: block" %>
    <%= form.text_field :pickup_address %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Carrier:</strong>
    <%= order.carrier_id %>
  </p>

  <p>
    <strong>Delivery address:</strong>
    <%= order.delivery_address %>
  </p>

  <p>
    <strong>Equipment type:</strong>
    <%= order.equipment_type %>
  </p>

  <p>
    <strong>Orderer:</strong>
    <%= order.orderer_id %>
  </p>

  <p>
    <strong>Pickup date:</strong>
    <%= order.pickup_date %>
  </p>

  <p>
    <strong>Pickup address:</strong>
    <%= order.pickup_address %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= order.status %>
  </p>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<h1>Orders</h1>

<table>
  <tfoot>
    <tr>
      <td colspan="3">
        <%= link_to 'New Order', new_order_path %>
      </td>
    </tr>
  </tfoot>
  <tbody>
    <% @orders.each do |order| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

      <!-- This currently shows something like this:

        Carrier: 8
        Delivery address: 5105M Fisher Street Saint-Laurent, QC H4T 1J8 Canada
        Equipment type: 0
        Orderer: 8
        Pickup date: 2023-05-01
        Pickup address: 975 Pacific Gate unit 18, Mississauga, ON L5T 1Y1
        Status: 0

        TODO: Improve this to show the actual values instead of the IDs
      -->
        <td class="description">
          <%= render order %>
        </td>

        <td class="actions">
          <ul>
            <li><%= link_to 'Show', order %></li>
            <li><%= link_to 'Edit', edit_order_path(order) %></li>
            <li>
              <%= link_to 'Destroy',
                           order, 
                          method: :delete,
                          data: { confirm: 'Are you sure?' } %>
            </li>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>