config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :orders
  resources :users
  resources :shippers
  resources :carriers
  resources :brokers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/shipper.rb
# frozen_string_literal: true

class Shipper < ApplicationRecord
  has_many :users, as: :org
  has_many :orders, as: :orderer
end

app/controllers/shippers_controller.rb
# frozen_string_literal: true

class ShippersController < ApplicationController
  before_action :set_shipper, only: %i[show edit update destroy]

  # GET /shippers or /shippers.json
  def index
    @shippers = Shipper.all
  end

  # GET /shippers/1 or /shippers/1.json
  def show; end

  # GET /shippers/new
  def new
    @shipper = Shipper.new
  end

  # GET /shippers/1/edit
  def edit; end

  # POST /shippers or /shippers.json
  def create
    @shipper = Shipper.new(shipper_params)

    respond_to do |format|
      if @shipper.save
        format.html do
          redirect_to shipper_url(@shipper),
                      notice: 'Shipper was successfully created.'
        end
        format.json { render :show, status: :created, location: @shipper }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @shipper.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /shippers/1 or /shippers/1.json
  def update
    respond_to do |format|
      if @shipper.update(shipper_params)
        format.html do
          redirect_to shipper_url(@shipper),
                      notice: 'Shipper was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @shipper }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @shipper.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /shippers/1 or /shippers/1.json
  def destroy
    @shipper.destroy

    respond_to do |format|
      format.html do
        redirect_to shippers_url, notice: 'Shipper was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_shipper
    @shipper = Shipper.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def shipper_params
    params.require(:shipper).permit(:address, :country, :email, :name, :phone)
  end
end

app/helpers/shippers_helper.rb
# frozen_string_literal: true

module ShippersHelper
end

app/views/shippers/_form.html.erb
<%= form_with(model: shipper) do |form| %>
  <% if shipper.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shipper.errors.count, "error") %> prohibited this shipper from being saved:</h2>

      <ul>
        <% shipper.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.number_field :country %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shippers/_shipper.html.erb
<div id="<%= dom_id shipper %>">
  <p>
    <strong>Address:</strong>
    <%= shipper.address %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= shipper.country %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= shipper.email %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= shipper.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= shipper.phone %>
  </p>

</div>

app/views/shippers/edit.html.erb
<h1>Editing shipper</h1>

<%= render "form", shipper: @shipper %>

<br>

<div>
  <%= link_to "Show this shipper", @shipper %> |
  <%= link_to "Back to shippers", shippers_path %>
</div>

app/views/shippers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shippers</h1>

<div id="shippers">
  <% @shippers.each do |shipper| %>
    <%= render shipper %>
    <p>
      <%= link_to "Show this shipper", shipper %>
    </p>
  <% end %>
</div>

<%= link_to "New shipper", new_shipper_path %>

app/views/shippers/new.html.erb
<h1>New shipper</h1>

<%= render "form", shipper: @shipper %>

<br>

<div>
  <%= link_to "Back to shippers", shippers_path %>
</div>

app/views/shippers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shipper %>

<div>
  <%= link_to "Edit this shipper", edit_shipper_path(@shipper) %> |
  <%= link_to "Back to shippers", shippers_path %>

  <%= button_to "Destroy this shipper", @shipper, method: :delete %>
</div>