config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :orders
  resources :users
  resources :shippers
  resources :carriers
  resources :brokers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/broker.rb
# frozen_string_literal: true

class Broker < ApplicationRecord
  has_many :users, as: :org
  has_many :orders, as: :orderer
end

app/controllers/brokers_controller.rb
# frozen_string_literal: true

class BrokersController < ApplicationController
  before_action :set_broker, only: %i[show edit update destroy]

  # GET /brokers or /brokers.json
  def index
    @brokers = Broker.all
  end

  # GET /brokers/1 or /brokers/1.json
  def show; end

  # GET /brokers/new
  def new
    @broker = Broker.new
  end

  # GET /brokers/1/edit
  def edit; end

  # POST /brokers or /brokers.json
  def create
    @broker = Broker.new(broker_params)

    respond_to do |format|
      if @broker.save
        format.html do
          redirect_to broker_url(@broker),
                      notice: 'Broker was successfully created.'
        end
        format.json { render :show, status: :created, location: @broker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @broker.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /brokers/1 or /brokers/1.json
  def update
    respond_to do |format|
      if @broker.update(broker_params)
        format.html do
          redirect_to broker_url(@broker),
                      notice: 'Broker was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @broker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @broker.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /brokers/1 or /brokers/1.json
  def destroy
    @broker.destroy

    respond_to do |format|
      format.html do
        redirect_to brokers_url, notice: 'Broker was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_broker
    @broker = Broker.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def broker_params
    params.require(:broker).permit(:address, :country, :email, :mc, :name,
                                   :phone, :usdot)
  end
end

app/helpers/brokers_helper.rb
# frozen_string_literal: true

module BrokersHelper
end

app/views/brokers/_broker.html.erb
<div id="<%= dom_id broker %>">
  <p>
    <strong>Address:</strong>
    <%= broker.address %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= broker.country %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= broker.email %>
  </p>

  <p>
    <strong>Mc:</strong>
    <%= broker.mc %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= broker.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= broker.phone %>
  </p>

  <p>
    <strong>Usdot:</strong>
    <%= broker.usdot %>
  </p>

</div>

app/views/brokers/_form.html.erb
<%= form_with(model: broker) do |form| %>
  <% if broker.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(broker.errors.count, "error") %> prohibited this broker from being saved:</h2>

      <ul>
        <% broker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.number_field :country %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :mc, style: "display: block" %>
    <%= form.text_field :mc %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :usdot, style: "display: block" %>
    <%= form.text_field :usdot %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/brokers/edit.html.erb
<h1>Editing broker</h1>

<%= render "form", broker: @broker %>

<br>

<div>
  <%= link_to "Show this broker", @broker %> |
  <%= link_to "Back to brokers", brokers_path %>
</div>

app/views/brokers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Brokers</h1>

<div id="brokers">
  <% @brokers.each do |broker| %>
    <%= render broker %>
    <p>
      <%= link_to "Show this broker", broker %>
    </p>
  <% end %>
</div>

<%= link_to "New broker", new_broker_path %>

app/views/brokers/new.html.erb
<h1>New broker</h1>

<%= render "form", broker: @broker %>

<br>

<div>
  <%= link_to "Back to brokers", brokers_path %>
</div>

app/views/brokers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @broker %>

<div>
  <%= link_to "Edit this broker", edit_broker_path(@broker) %> |
  <%= link_to "Back to brokers", brokers_path %>

  <%= button_to "Destroy this broker", @broker, method: :delete %>
</div>